### ISSUE TITLE
Auktion kaster NullPointer

### ISSUE THREAD

**Issue by FredMar** [lupuscarnis/CDIO-Final#10]
![udklip](https://user-images.githubusercontent.com/16269671/34869974-f83b612e-f788-11e7-9d50-6c26c20ef577.JPG)

Forsøger at gennemføre auktion men får NullPointer (måske ved sidste player)

**Comment by hjaltebaekgaard** [comment]
auction initialises Player highestBidder = null, then sets player from player array to highestBidder (null)

**Comment by hjaltebaekgaard** [comment]
it's still not fixed, players from the active player array must not be set to another player either (I'm quite sure this is the cause of the prison bug, as it messes with who's turn it is).
And the forced auctions due to the canAfford check (which in my opinion shouldn't be there)
